### ISSUE TITLE
Support tuples

### ISSUE THREAD

**Issue by piever** [JuliaData/Tables.jl#87] opened 2019-04-29 14:13 UTC
In Julia 1.2 there is a `getproperty(t::Tuple, i::Int)` method now, so Tables could in principle support "tuple based tables". If there were here a method for `Tables.Schema(::Type{<:Tuple})` to generate a "nameless schema" I suspect the IndexedTables implementation would work already for tables of tuples.

**Comment by quinnj** [comment] 2019-05-23 22:08
Duplicate of #6

**Closed as completed by quinnj** 2019-05-23 22:08 UTC
