### ISSUE TITLE
Travis tests failing: Unsatistfiable requirements for TableTraits

### ISSUE THREAD

**Issue by ablaom** [JuliaData/Tables.jl#88] opened 2019-05-01 08:20 UTC
From [this](https://travis-ci.org/JuliaData/Tables.jl/jobs/525980722) build attempt:

```
ERROR: Unsatisfiable requirements detected for package TableTraits [3783bdb8]:
 TableTraits [3783bdb8] log:
 ├─possible versions are: [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.1, 1.0.0] or uninstalled
 ├─restricted to versions * by Tables [bd369af6], leaving only versions [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.1, 1.0.0]
 │ └─Tables [bd369af6] log:
 │   ├─possible versions are: 0.2.0 or uninstalled
 │   └─Tables [bd369af6] is fixed to version 0.2.0
 ├─restricted to versions 1.0.0 by an explicit requirement, leaving only versions 1.0.0
 └─restricted by compatibility requirements with QueryOperators [2aef5ad7] to versions: [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.1] — no versions left

etc
```

**Comment by fredrikekre** [comment] 2019-05-02 12:07
The interesting part from the log was left out here, the problem is: https://github.com/JuliaRegistries/General/blob/17357a5c1c15c67fa8ec591c82f3263af6befbef/Q/QueryOperators/Compat.toml#L20
QueryOperators is not compatible with IteratorInterfaceExtensions 1.0

**Comment by nalimilan** [comment] 2019-05-02 12:22
Looks like it's caused by https://github.com/JuliaLang/Pkg.jl/issues/110. So the only solution is to port QueryOperators to  IteratorInterfaceExtensions 1.0. @davidanthoff Is that going to take a lot of work?

**Comment by nalimilan** [comment] 2019-05-02 12:40
ActuallyQueryOperators already supports IteratorInterfaceExtensions 1.0: its Project.toml file doesn't have an upper bound, and tests pass. See https://github.com/JuliaRegistries/General/pull/494.

**Comment by quinnj** [comment] 2019-05-04 04:29
Closing since this isn't a Tables.jl issue.

**Closed as completed by quinnj** 2019-05-04 04:29 UTC
